// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BookMarkItem: typeof import('./components/BookMarkItem.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
  }
}

export { }
